### ISSUE TITLE
Does `Instance<T>` violate ECS pattern?

### ISSUE THREAD

**Issue by Nul-led** [Zeenobit/moonshine_kind#2]
Doesn't this crate kind of conflict with the idea of an ECS? According to definition, entities should just be identifiers which don't hold data.

**Comment by Zeenobit** [comment]
An `Instance<T>` doesn't carry any "data" either. It carries type information.

I define "data" as the components attached to the entity. An instance carries/references none of that.

It's purely a matter of readability and safety. If I have a system which deals with a given subset of entities, I'd like to be able to make certain assumptions about the entities I'm dealing with. If I have:

```rust
struct FruitBasket {
    fruits: Vec<Entity>,
}
```

That tells me the `FruitBasket` may contain any entity. Hopefully it's a "Fruit". But it could be a bike! Or a person!

But if I have:
```rust
struct FruitBasket {
    fruits: Vec<Instance<Fruit>>,
}
```
I can make a reasonable assumption (not a guarantee!) that those entities are all fruits.
